apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    http_port = 3000
    [auth]
    disable_login_form = false
    [users]
    allow_sign_up = false
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        jsonData:
          maxLines: 1000
