apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['platform-service.default.svc.cluster.local:5000']

