apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /var/log/positions.yaml

    clients:
      - url: http://loki-service:3100/loki/api/v1/push

    scrape_configs:
      - job_name: "kubernetes-containers"
        static_configs:
          - targets:
              - localhost
            labels:
              job: "kubernetes-containers"
              __path__: "/var/log/containers/*.log"


