apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: monitoring
data:
  vector.yaml: |
    data_dir: "/var/lib/vector"

    sources:
      kubernetes_logs:
        type: file
        include:
          - /var/log/containers/*.log
        read_from: beginning

    transforms:
      parse_json:
        type: remap
        inputs: ["kubernetes_logs"]
        source: |
          . = parse_json!(.message)

    sinks:
      loki:
        type: loki
        inputs: ["parse_json"]
        endpoint: "http://loki:3100"
        encoding:
          codec: json
        labels:
          job: "vector"
