apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
      - name: platform
        image: platform:latest
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: platform-config
        resources:
          limits:
            cpu: "500m"      
            memory: "512Mi"  
          requests:
            cpu: "250m"       
            memory: "256Mi"   
