apiVersion: v1
kind: Service
metadata:
  name: platform-service
spec:
  selector:
    app: platform  
  ports:
    - protocol: TCP
      port: 8000  
      targetPort: 8000  
      nodePort: 30000  
  type: NodePort
